/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UFES.prova1.View;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author nandi
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionario = new javax.swing.JMenu();
        menuManterFuncionario = new javax.swing.JMenuItem();
        menuBuscarFuncionario = new javax.swing.JMenuItem();
        menuSalario = new javax.swing.JMenu();
        menuCalcularSalario = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestão de pessoas");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuFuncionario.setText("Funcionário");

        menuManterFuncionario.setText("Manter Funcionario");
        menuFuncionario.add(menuManterFuncionario);

        menuBuscarFuncionario.setText("Buscar Funcionario");
        menuFuncionario.add(menuBuscarFuncionario);

        jMenuBar1.add(menuFuncionario);

        menuSalario.setText("Salário");

        menuCalcularSalario.setText("Calcular Salário");
        menuCalcularSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalcularSalarioActionPerformed(evt);
            }
        });
        menuSalario.add(menuCalcularSalario);

        jMenuBar1.add(menuSalario);

        menuFerramentas.setText("Ferramentas");
        jMenuBar1.add(menuFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCalcularSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalcularSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCalcularSalarioActionPerformed

    /**
     * @param args the command line arguments
     */

    public JMenuItem getMenuBuscarFuncionario() {
        return menuBuscarFuncionario;
    }

    public void setMenuBuscarFuncionario(JMenuItem menuBuscarFuncionario) {
        this.menuBuscarFuncionario = menuBuscarFuncionario;
    }

    public JMenu getMenuFerramentas() {
        return menuFerramentas;
    }

    public void setMenuFerramentas(JMenu menuFerramentas) {
        this.menuFerramentas = menuFerramentas;
    }

    public JMenu getMenuFuncionario() {
        return menuFuncionario;
    }

    public void setMenuFuncionario(JMenu menuFuncionario) {
        this.menuFuncionario = menuFuncionario;
    }

    public JMenuItem getMenuManterFuncionario() {
        return menuManterFuncionario;
    }

    public void setMenuManterFuncionario(JMenuItem menuManterFuncionario) {
        this.menuManterFuncionario = menuManterFuncionario;
    }

    public JMenu getMenuSalario() {
        return menuSalario;
    }

    /**
     * @param args the command line arguments
     */
    public void setMenuSalario(JMenu menuSalario) {
        this.menuSalario = menuSalario;
    }

    public JMenuItem getMenuCalcularSalario() {
        return menuCalcularSalario;
    }

    public void setMenuCalcularSalario(JMenuItem menuCalcularSalario) {
        this.menuCalcularSalario = menuCalcularSalario;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBuscarFuncionario;
    private javax.swing.JMenuItem menuCalcularSalario;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenuItem menuManterFuncionario;
    private javax.swing.JMenu menuSalario;
    // End of variables declaration//GEN-END:variables
}
